---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Check ffmpeg binary exists
      ansible.builtin.stat:
        path: /root/bin/ffmpeg
      register: ffmpeg_binary

    - name: Assert ffmpeg exists
      ansible.builtin.assert:
        that:
          - ffmpeg_binary.stat.exists
        fail_msg: "FFmpeg binary not found at /root/bin/ffmpeg"
        success_msg: "FFmpeg binary found"

    - name: Check ffprobe binary exists
      ansible.builtin.stat:
        path: /root/bin/ffprobe
      register: ffprobe_binary

    - name: Assert ffprobe exists
      ansible.builtin.assert:
        that:
          - ffprobe_binary.stat.exists
        fail_msg: "FFprobe binary not found at /root/bin/ffprobe"
        success_msg: "FFprobe binary found"

    - name: Get ffmpeg version
      ansible.builtin.command:
        cmd: /root/bin/ffmpeg -version
      register: ffmpeg_version
      changed_when: false

    - name: Display ffmpeg version
      ansible.builtin.debug:
        msg: "{{ ffmpeg_version.stdout_lines[0] }}"

    - name: Test ffmpeg can encode
      ansible.builtin.shell: |
        /root/bin/ffmpeg -f lavfi -i testsrc=duration=1:size=320x240:rate=1 -f null -
      register: ffmpeg_encode_test
      changed_when: false

    - name: Assert encoding works
      ansible.builtin.assert:
        that:
          - ffmpeg_encode_test.rc == 0
        fail_msg: "FFmpeg encoding test failed"
        success_msg: "FFmpeg encoding test passed"
